# Generated by Django 5.2.12 on 2026-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image'), ('AUDIO', 'Audio')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('is_fake', models.BooleanField(default=False)),
                ('confidence', models.FloatField()),
                ('reasons', models.JSONField(default=list)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
